$ipc = qs -c noctalia-shell ipc call

# Core binds
bind = SUPER, SPACE, exec, $ipc launcher toggle
bind = SUPER, comma, exec, $ipc controlCenter toggle
# bind = SUPER, comma, exec, $ipc settings toggle
bind = SUPER SHIFT, C, exec, $ipc sessionMenu toggle

# Media keys
bindel = , XF86AudioRaiseVolume, exec, $ipc volume increase
bindel = , XF86AudioLowerVolume, exec, $ipc volume decrease
bindel = , XF86AudioMute, exec, $ipc volume muteOutput
bindel = , XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = , XF86MonBrightnessDown, exec, $ipc brightness decrease
