[colors.primary]
background = '#000000'
foreground = '#e6f0ff'

[colors.selection]
text = '#e6f0ff'
background = '#cc5200'

[colors.cursor]
text = '#000000'
cursor = '#f35c25'

[colors.normal]
black   = '#000000'
red     = '#cc3370'
green   = '#9ad66e'
yellow  = '#dbab7b'
blue    = '#b34a23'
magenta = '#b65b3a'
cyan    = '#F35C25'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f92'
green   = '#ace086'
yellow  = '#e8c097'
blue    = '#ffc09f'
magenta = '#91342b'
cyan    = '#865535'
white   = '#ffffff'
