[colors.primary]
background = '#0a0a15'
foreground = '#e6f0ff'

[colors.selection]
text = '#e6f0ff'
background = '#cc5200'

[colors.cursor]
text = '#0a0a15'
cursor = '#ff6600'

[colors.normal]
black   = '#0A0A15'
red     = '#ff0c00'
green   = '#2dff00'
yellow  = '#ffd100'
blue    = '#f26000'
magenta = '#762f00'
cyan    = '#FF6600'
white   = '#ffece0'

[colors.bright]
black   = '#a5968c'
red     = '#ff483f'
green   = '#6cff4c'
yellow  = '#ffdf4c'
blue    = '#ff7c26'
magenta = '#ff934c'
cyan    = '#ffba8c'
white   = '#fff7f2'
