exec-once = uwsm app -- hypridle
exec-once = uwsm app -- waybar
exec-once = uwsm app -- swaync
exec-once = uwsm app -- swaybg -i ~/.config/system-setup/current/background -m fill
exec-once = uwsm app -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = uwsm app -- wl-clip-persist --clipboard regular --all-mime-type-regex '^(?!x-kde-passwordManagerHint).+'

