# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/
# Application bindings
$terminal = ghostty
$browser = firefox
$webapp = chromium --new-window --ozone-platform=wayland --app
$mainMod = SUPER

# Use defaults system-setup defaults
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/looknfeel.conf

input {
  kb_layout = us
  kb_variant = altgr-intl
  kb_model =
  kb_options = ctrl:nocaps
  kb_rules =

  follow_mouse = 1


  touchpad {
      natural_scroll = false
      disable_while_typing = true
      scroll_factor = 1.0
      tap-to-click = true
  }

  repeat_rate = 40
  repeat_delay = 600
  sensitivity = 1.0

}

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Optional: DankMaterialShell & Noctalia integration 
source = ~/.config/hypr/dank.conf

# Change your personal monitor setup in here to keep the main config portable
# source = ~/.config/hypr/places/laptop.conf


source = ./dms/cursor.conf

source = ./dms/outputs.conf
