[colors.primary]
background = '#09070d'
foreground = '#f0f0f0'

[colors.selection]
text = '#f0f0f0'
background = '#5b748c'

[colors.cursor]
text = '#09070d'
cursor = '#a2d2ff'

[colors.normal]
black   = '#130f1a'
red     = '#ff729d'
green   = '#7fff90'
yellow  = '#fff772'
blue    = '#88bef2'
magenta = '#274f76'
cyan    = '#a2d2ff'
white   = '#eff7ff'

[colors.bright]
black   = '#999fa5'
red     = '#ff9fbc'
green   = '#a5ffb1'
yellow  = '#fffaa5'
blue    = '#afd8ff'
magenta = '#bddfff'
cyan    = '#d5eaff'
white   = '#f8fbff'
