monitor = HDMI-A-2, 3840x2160@60.000, 1920x0, 1.5
monitor = DP-3, 1920x1200@59.950, 0x240, 1
workspace = 1, monitor:DP-3, default:true
workspace = 2, monitor:HDMI-A-2, default:true

# === thet ===
windowrule = float on, match:class ^(com.example.my_proj)$
windowrule = size 1600 1200, match:class ^(com.example.my_proj)$
windowrule = workspace 4 silent, match:class ^(com.example.my_proj)$
windowrule = no_initial_focus on, match:class ^(com.example.my_proj)$

# === thet ===
windowrule = float on, match:class ^(thet)$
windowrule = size 1600 1200, match:class ^(thet)$
windowrule = workspace 4 silent, match:class ^(thet)$
windowrule = no_initial_focus on, match:class ^(thet)$
