#################################################################### Options
set -g mouse on # enable mouse support
set -g base-index 1 # start window numbering at 1
# set -g default-command "/bin/bash -i" # start bash in interactive mode
# UPDATE, we respect the $SHELL
setw -g pane-base-index 1 # start pane numbering at 1
set -g renumber-windows on  # renumber windows when a window is closed
setw -g mode-keys vi # Use vim keybindings in copy mode
set -g escape-time 10  # Fix ESC delay in vim
set -as terminal-features ',*:RGB'
set-option -g allow-rename off


##################################################################### Keybinds
# let's jsut use C-B
# unbind C-b  # Prefix Key
# set -g prefix C-a
# bind C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Use vim keybindings in copy mode
unbind-key -T copy-mode-vi v
bind-key -T copy-mode-vi v \
  send-keys -X begin-selection

bind-key -T copy-mode-vi 'C-v' \
  send-keys -X rectangle-toggle

bind-key -T copy-mode-vi y \
  send-keys -X copy-pipe-and-cancel "wl-copy"

bind-key -T copy-mode-vi MouseDragEnd1Pane \
  send-keys -X copy-pipe-and-cancel "wl-copy"


# New window in the current pane's directory.
bind c new-window -c '#{pane_current_path}'

# Window navigation.
bind n next-window
bind p previous-window

# Pane navigation: vim-style, killing and renaiming
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind x kill-pane
bind z resize-pane -Z
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# Splits in current pane's directory.
# | means side-by-side panes, so it uses -h.
# - means stacked panes, so it uses -v.
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

# Break current pane into a new detached window.
bind b break-pane

# WINDOW TITLE SETTINGS
# prevent tmux from grabbing the shell’s own title changes

# Close tmux, deattach
bind \\ detach-client
bind q detach-client

####################################################################### Theming
set-option -g status-position top
set -g status-style bg=default,fg=white,bright
set -g status-right "[#S]"

# disable tmux’s automatic window renaming
# set-option -g automatic-rename off

# control the title shown in your status bar
# set-option -g window-status-format      "#I:#W"
# set-option -g window-status-current-format "#[bold]#I:#W"

# update your terminal emulator’s title to “session:window”
set-option -g set-titles on
set-option -g set-titles-string "#S:#W"

# run-shell ~/.config/tmux/tmux-sensible.tmux
