# dstask aliases
alias d='dstask next'
alias da='dstask add'
alias ds='dstask start'
alias dd='dstask done'
alias dc='dstask context'
alias dm='dstask modify'
alias dl='dstask log'
alias de='dstask edit'
alias dn='dstask note'
alias dsync='dstask sync'
alias dnote='dstask note'
alias dstop='dstask stop'
alias drm='dstask remove'

